import { cp, mkdir, readdir } from 'node:fs/promises'
import path from 'node:path'

/**
 * Copies the MediaPipe vision WASM runtime out of node_modules and into
 * `public/mediapipe-wasm/` so the try-on filter loads it from our own origin.
 *
 * The campaign app pulled this from `jsdelivr/@mediapipe/tasks-vision@latest`,
 * which meant an upstream release could break the filter with no deploy on our
 * side. Serving the copy that ships with the installed package also makes it
 * impossible for the JS and the WASM to drift apart.
 *
 * ~36MB, so it stays out of git (see .gitignore) and is regenerated by
 * `postinstall` and `prebuild`.
 */

const SOURCE = path.resolve(process.cwd(), 'node_modules', '@mediapipe', 'tasks-vision', 'wasm')
const TARGET = path.resolve(process.cwd(), 'public', 'mediapipe-wasm')

const run = async () => {
  const files = await readdir(SOURCE).catch(() => null)

  if (!files?.length) {
    // Not fatal: a CI job that only lints has no reason to fail here.
    console.warn(`[sync-mediapipe] no WASM found at ${SOURCE} — skipping.`)
    return
  }

  await mkdir(TARGET, { recursive: true })
  await cp(SOURCE, TARGET, { recursive: true })

  console.log(`[sync-mediapipe] copied ${files.length} file(s) to public/mediapipe-wasm/`)
}

run().catch((error) => {
  console.error(error)
  process.exit(1)
})
